apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: marketing-agents
type: Opaque
data:
  OPENAI_API_KEY: ""  # Base64 encoded OpenAI API key
  JWT_SECRET_KEY: ""  # Base64 encoded JWT secret
  MONGODB_URI: ""     # Base64 encoded MongoDB connection string
  REDIS_URI: ""       # Base64 encoded Redis connection string
  NEO4J_URI: ""       # Base64 encoded Neo4j connection string
